version: '3'

services:
  google_home_broadcast:
    build: ./google_home_broadcast
    image: ambienthealthcare/google_home_broadcast
    container_name: google_home_broadcast
    depends_on:
     - mosquitto
    restart: always
    network_mode: "host"
